services:
  postgres:
    image: postgres:16
    container_name: postgres_ducklake
    environment:
      POSTGRES_DB: ducklake_catalog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ducklake_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ducklake_catalog"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: minio_ducklake
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # API
      - "9090:9090" # Console
    volumes:
      - minio_data:/data
    networks:
      - ducklake_net
    command: server /data --console-address ":9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  minio_data:

networks:
  ducklake_net:
    driver: bridge
